name: build-uniapp-vue3

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x, 22.x, 23.x, 24.x] # node>=18.x

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build with-uniapp-vue3
        working-directory: ./demos/with-uniapp-vue3
        run: |
          yarn install
          yarn run build:h5
