name: build-demo

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 21.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      #   - uses: actions/checkout@v4
      - name: Build react-demo
        working-directory: ./demos/react-demo
        run: |
          pnpm install
          pnpm run build

      - name: Build vue-demo
        working-directory: ./demos/vue-demo
        run: |
          pnpm install
          pnpm run build

    #   - run: cd demos/vue-demo
    #   - run: pnpm install
    #   - run: pnpm run build

    #   - run: cd demos/vue3-demo
    #   - run: pnpm install
    #   - run: pnpm run build

    #   - run: cd demos/with-react-vite
    #   - run: pnpm install
    #   - run: pnpm run build
